# 1-. Starting: loading data

In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import mypy as py
import argparse
from pathlib import Path


In [2]:
%load_ext autoreload
%autoreload 2

import os
os.chdir(str(Path("../")))

from src import duplicado
from src import titulo
from src import faltantes
from src import conv_dado_num

In [3]:
df_carro = pd.read_csv(Path("data/vehicles.csv"))

# 2-. Exploratory data analysis

In [4]:
df_carro.info()
df_carro.describe(include = 'all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   price         51525 non-null  int64  
 1   model_year    47906 non-null  float64
 2   model         51525 non-null  object 
 3   condition     51525 non-null  object 
 4   cylinders     46265 non-null  float64
 5   fuel          51525 non-null  object 
 6   odometer      43633 non-null  float64
 7   transmission  51525 non-null  object 
 8   type          51525 non-null  object 
 9   paint_color   42258 non-null  object 
 10  is_4wd        25572 non-null  float64
 11  date_posted   51525 non-null  object 
 12  days_listed   51525 non-null  int64  
dtypes: float64(4), int64(2), object(7)
memory usage: 5.1+ MB


price    model_year       model  condition     cylinders  \
count    51525.000000  47906.000000       51525      51525  46265.000000   
unique            NaN           NaN         100          6           NaN   
top               NaN           NaN  ford f-150  excellent           NaN   
freq              NaN           NaN        2796      24773           NaN   
mean     12132.464920   2009.750470         NaN        NaN      6.125235   
std      10040.803015      6.282065         NaN        NaN      1.660360   
min          1.000000   1908.000000         NaN        NaN      3.000000   
25%       5000.000000   2006.000000         NaN        NaN      4.000000   
50%       9000.000000   2011.000000         NaN        NaN      6.000000   
75%      16839.000000   2014.000000         NaN        NaN      8.000000   
max     375000.000000   2019.000000         NaN        NaN     12.000000   

         fuel       odometer transmission   type paint_color   is_4wd  \
count   51525   43633.000000        51525  51525       42258  25572.0   
unique      5            NaN            3     13          12      NaN   
top       gas            NaN    automatic    SUV       white      NaN   
freq    47288            NaN        46902  12405       10029      NaN   
mean      NaN  115553.461738          NaN    NaN         NaN      1.0   
std       NaN   65094.611341          NaN    NaN         NaN      0.0   
min       NaN       0.000000          NaN    NaN         NaN      1.0   
25%       NaN   70000.000000          NaN    NaN         NaN      1.0   
50%       NaN  113000.000000          NaN    NaN         NaN      1.0   
75%       NaN  155000.000000          NaN    NaN         NaN      1.0   
max       NaN  990000.000000          NaN    NaN         NaN      1.0   

       date_posted  days_listed  
count        51525  51525.00000  
unique         354          NaN  
top     2019-03-17          NaN  
freq           186          NaN  
mean           NaN     39.55476  
std            NaN     28.20427  
min            NaN      0.00000  
25%            NaN     19.00000  
50%            NaN     33.00000  
75%            NaN     53.00000  
max            NaN    271.00000

In [5]:
# Verificar cabeçalhos de tabela
titulo.cabecalhos_df(df_carro)

price  model_year           model  condition  cylinders fuel  odometer  \
0       9400      2011.0          bmw x5       good        6.0  gas  145000.0   
1      25500         NaN      ford f-150       good        6.0  gas   88705.0   
2       5500      2013.0  hyundai sonata   like new        4.0  gas  110000.0   
3       1500      2003.0      ford f-150       fair        8.0  gas       NaN   
4      14900      2017.0    chrysler 200  excellent        4.0  gas   80903.0   
...      ...         ...             ...        ...        ...  ...       ...   
51520   9249      2013.0   nissan maxima   like new        6.0  gas   88136.0   
51521   2700      2002.0     honda civic    salvage        4.0  gas  181500.0   
51522   3950      2009.0  hyundai sonata  excellent        4.0  gas  128000.0   
51523   7455      2013.0  toyota corolla       good        4.0  gas  139573.0   
51524   6300      2014.0   nissan altima       good        4.0  gas       NaN   

      transmission    type paint_color  is_4wd date_posted  days_listed  
0        automatic     SUV         NaN     1.0  2018-06-23           19  
1        automatic  pickup       white     1.0  2018-10-19           50  
2        automatic   sedan         red     NaN  2019-02-07           79  
3        automatic  pickup         NaN     NaN  2019-03-22            9  
4        automatic   sedan       black     NaN  2019-04-02           28  
...            ...     ...         ...     ...         ...          ...  
51520    automatic   sedan       black     NaN  2018-10-03           37  
51521    automatic   sedan       white     NaN  2018-11-14           22  
51522    automatic   sedan        blue     NaN  2018-11-15           32  
51523    automatic   sedan       black     NaN  2018-07-02           71  
51524    automatic   sedan         NaN     NaN  2018-06-05           10  

[51525 rows x 13 columns]

In [6]:
# Duplicados explicitos na tabela
duplicado.df_duplicado(df_carro)

Quantidade de duplicados é = 0


In [7]:
# Quantidade de valores faltantes por colunas
df_carro.isnull().sum()

price               0
model_year       3619
model               0
condition           0
cylinders        5260
fuel                0
odometer         7892
transmission        0
type                0
paint_color      9267
is_4wd          25953
date_posted         0
days_listed         0
dtype: int64

*2.1 Tratamento de dados faltantes por colunas*

In [8]:
df_carro = pd.read_csv(Path("data/vehicles.csv"), keep_default_na=False)
df_carro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   price         51525 non-null  int64 
 1   model_year    51525 non-null  object
 2   model         51525 non-null  object
 3   condition     51525 non-null  object
 4   cylinders     51525 non-null  object
 5   fuel          51525 non-null  object
 6   odometer      51525 non-null  object
 7   transmission  51525 non-null  object
 8   type          51525 non-null  object
 9   paint_color   51525 non-null  object
 10  is_4wd        51525 non-null  object
 11  date_posted   51525 non-null  object
 12  days_listed   51525 non-null  int64 
dtypes: int64(2), object(11)
memory usage: 5.1+ MB


In [9]:
# 2.1.1 Tratamento da coluna: 'model_year'
faltantes.faltante_categorico(df_carro, 'model_year', '0')
conv_dado_num.conv_str_int(df_carro, 'model_year')
df_carro['model_year'].unique()

Valores univocos da coluna: model_year, são: ['2011.0' '0' '2013.0' '2003.0' '2017.0' '2014.0' '2015.0' '2012.0'
 '2008.0' '2018.0' '2009.0' '2010.0' '2007.0' '2004.0' '2005.0' '2001.0'
 '2006.0' '1966.0' '1994.0' '2019.0' '2000.0' '2016.0' '1993.0' '1999.0'
 '1997.0' '2002.0' '1981.0' '1995.0' '1996.0' '1975.0' '1998.0' '1985.0'
 '1977.0' '1987.0' '1974.0' '1990.0' '1992.0' '1991.0' '1972.0' '1967.0'
 '1988.0' '1969.0' '1989.0' '1978.0' '1965.0' '1979.0' '1968.0' '1986.0'
 '1980.0' '1964.0' '1963.0' '1984.0' '1982.0' '1973.0' '1970.0' '1955.0'
 '1971.0' '1976.0' '1983.0' '1954.0' '1962.0' '1948.0' '1960.0' '1908.0'
 '1961.0' '1936.0' '1949.0' '1958.0' '1929.0']
<class 'pandas.core.series.Series'>
RangeIndex: 51525 entries, 0 to 51524
Series name: model_year
Non-Null Count  Dtype
--------------  -----
51525 non-null  int64
dtypes: int64(1)
memory usage: 402.7 KB
None


array([2011,    0, 2013, 2003, 2017, 2014, 2015, 2012, 2008, 2018, 2009,
       2010, 2007, 2004, 2005, 2001, 2006, 1966, 1994, 2019, 2000, 2016,
       1993, 1999, 1997, 2002, 1981, 1995, 1996, 1975, 1998, 1985, 1977,
       1987, 1974, 1990, 1992, 1991, 1972, 1967, 1988, 1969, 1989, 1978,
       1965, 1979, 1968, 1986, 1980, 1964, 1963, 1984, 1982, 1973, 1970,
       1955, 1971, 1976, 1983, 1954, 1962, 1948, 1960, 1908, 1961, 1936,
       1949, 1958, 1929])

In [10]:
# 2.1.1 Tratamento da coluna: 'model_year'
df_carro['model_year'] = df_carro['model_year'].replace(0, 'unknown')
df_carro['model_year'].unique()

array([2011, 'unknown', 2013, 2003, 2017, 2014, 2015, 2012, 2008, 2018,
       2009, 2010, 2007, 2004, 2005, 2001, 2006, 1966, 1994, 2019, 2000,
       2016, 1993, 1999, 1997, 2002, 1981, 1995, 1996, 1975, 1998, 1985,
       1977, 1987, 1974, 1990, 1992, 1991, 1972, 1967, 1988, 1969, 1989,
       1978, 1965, 1979, 1968, 1986, 1980, 1964, 1963, 1984, 1982, 1973,
       1970, 1955, 1971, 1976, 1983, 1954, 1962, 1948, 1960, 1908, 1961,
       1936, 1949, 1958, 1929], dtype=object)

In [11]:
# 2.1.2 Tratamento da coluna: 'cylinders'
faltantes.faltante_categorico(df_carro, 'cylinders', '0')
conv_dado_num.conv_str_int(df_carro, 'cylinders')
df_carro['cylinders'] = df_carro['cylinders'].replace(0, 'unknown')
df_carro['cylinders'].unique()

Valores univocos da coluna: cylinders, são: ['6' '4' '8' '0' '5' '10' '3' '12']
<class 'pandas.core.series.Series'>
RangeIndex: 51525 entries, 0 to 51524
Series name: cylinders
Non-Null Count  Dtype
--------------  -----
51525 non-null  int64
dtypes: int64(1)
memory usage: 402.7 KB
None


array([6, 4, 8, 'unknown', 5, 10, 3, 12], dtype=object)

In [12]:
# 2.1.3 Tratamento da coluna: 'odometer'
faltantes.faltante_categorico(df_carro, 'odometer', '0')
conv_dado_num.conv_str_int(df_carro, 'odometer')
df_carro['odometer'] = df_carro['odometer'].replace(0, 'unknown')
df_carro['odometer'].unique()

Valores univocos da coluna: odometer, são: ['145000.0' '88705.0' '110000.0' ... '121778.0' '181500.0' '139573.0']
<class 'pandas.core.series.Series'>
RangeIndex: 51525 entries, 0 to 51524
Series name: odometer
Non-Null Count  Dtype
--------------  -----
51525 non-null  int64
dtypes: int64(1)
memory usage: 402.7 KB
None


array([145000, 88705, 110000, ..., 121778, 181500, 139573], dtype=object)

In [13]:
# 2.1.4 Tratamento da coluna: 'paint_color'
faltantes.faltante_categorico(df_carro, 'paint_color', 'unknown')

Valores univocos da coluna: paint_color, são: ['unknown' 'white' 'red' 'black' 'blue' 'grey' 'silver' 'custom' 'orange'
 'yellow' 'brown' 'green' 'purple']


In [16]:
# 2.1.5 Tratamento da coluna: 'is_4wd'
faltantes.faltante_categorico(df_carro, 'is_4wd', '0')
conv_dado_num.conv_str_int(df_carro, 'is_4wd')
df_carro['is_4wd'].unique()

Valores univocos da coluna: is_4wd, são: [1 0]
<class 'pandas.core.series.Series'>
RangeIndex: 51525 entries, 0 to 51524
Series name: is_4wd
Non-Null Count  Dtype
--------------  -----
51525 non-null  int64
dtypes: int64(1)
memory usage: 402.7 KB
None


array([1, 0])

In [20]:
df_carro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   price         51525 non-null  int64 
 1   model_year    51525 non-null  object
 2   model         51525 non-null  object
 3   condition     51525 non-null  object
 4   cylinders     51525 non-null  object
 5   fuel          51525 non-null  object
 6   odometer      51525 non-null  object
 7   transmission  51525 non-null  object
 8   type          51525 non-null  object
 9   paint_color   51525 non-null  object
 10  is_4wd        51525 non-null  int64 
 11  date_posted   51525 non-null  object
 12  days_listed   51525 non-null  int64 
dtypes: int64(3), object(10)
memory usage: 5.1+ MB
